# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "Setup"
version = "1.0.0"  # Semantic Versionning is used: https://semver.org/
description = "The setup extension for the streaming."
category = "Streaming"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "extension", "streaming"]  # Search keywords for the Extension Manager
preview_image = "data/preview.png"  # Preview to show in the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI
repository = ""  # URL of the extension source repository

[dependencies]
"omni.kit.usd.layers" = {}
"omni.activity.ui" = {order=1000}   # Progress activity messages
"omni.kit.quicklayout" = {}
"omni.kit.viewport.utility" = {}
"omni.conditioning_for_precise_visual_generative_ai.messaging" = {}  # Required messaging extension
"omni.ai.viewport.core" = {}

[settings.app]
useFabricSceneDelegate = true  # Turn on the Fabric scene delegate by default

[settings.exts."omni.conditioning_for_precise_visual_generative_ai.setup"]
menu_visible = false

[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.hello.world"
name = "omni.conditioning_for_precise_visual_generative_ai.setup"

[documentation]
pages = [
    "docs/CHANGELOG.md",
]

[[test]]
dependencies = [
    "omni.app.conditioning_for_precise_visual_generative_ai",
    "omni.kit.mainwindow",
    "omni.kit.ui_test",
]

args = [
    "--/app/layout/name=default",
    "--/app/fastShutdown=1",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/height=720",
    "--/app/window/scaleToMonitor=false",
    "--/app/window/width=1280",
    "--/exts/omni.kit.viewport.window/startup/windowName=Viewport",
    "--no-window",
    "--reset-user"
]
