########################################################################################################################
# Dependencies:
########################################################################################################################

[[dependency]]
python = "../../_build/target-deps/python"
packages = [
    "watchdog==0.10.4",
    "websocket-client==1.8.0",
    "better-profanity==0.7.0",
]
target = "../../_build/target-deps/pip_prebundle" # This folder will be linked into 'example.mixed_ext' extension (see premake file)
platforms = ["*"]
download_only = false
append_to_install_folder = true
# gather_licenses_path = "../../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
